name: Bug Report
description: File a bug report to help us improve cargo-commitlint
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your commitlint.toml configuration (if applicable)
      render: toml
      placeholder: |
        [rules]
        [rules.type]
        enum = ["feat", "fix"]

  - type: textarea
    id: commit-message
    attributes:
      label: Commit Message
      description: The commit message that caused the issue (if applicable)
      placeholder: feat: example commit message

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: rustc 1.75.0 (82e1608df 2023-12-21)
    validations:
      required: true

  - type: input
    id: cargo-commitlint-version
    attributes:
      label: cargo-commitlint Version
      description: Output of `cargo commitlint --version` or version from Cargo.toml if building from source
      placeholder: cargo-commitlint 0.1.0

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or logs
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant information above
          required: true

