name: Question
description: Ask a question about cargo-commitlint
title: "[Question]: "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about cargo-commitlint? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your question.
      placeholder: I'm trying to...

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What have you already tried or researched?
      placeholder: |
        - I've read the documentation on...
        - I've tried...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and documentation
          required: true
        - label: I have checked the README and examples
          required: true

